### ISSUE TITLE
12.0.2 disable_ca_verification not working

### ISSUE THREAD

**Issue by just-another-random-person** [misson20000/exefs_patches#15]
**Which patch is broken?**
disable_ca_verification

**Describe the bug**
Connecting to a server with a self-signed certificate, with disable_ca_verification patch on a clean Atmosphere install:

- Console 1 (Current version in settings: 12.0.2|AMS M.19.3|E) has a connection error and server has the following error:
  - ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1076)

- Console 2 (Current version in setting: 11.0.1|AMS M.18.1|E, old but clean Atmos install with disable_ca_verification) connects successfully with no error.

**Firmware version:**
12.0.2

**Comment by bundat** [comment]
Additional tests I did:

On console 2:
- removed disable_ca_verification (leaving clean [old] Atmos install, version 11.0.1|AMS M.18.1|E in settings)
  - got the same SSL bad cert error on server
 - deleted all files from SD card, used brand new latest Atmos install, version 11.0.1|AMS M.19.3|E in settings, then added disable_ca_verification
   -  connects successfully no error

On console 1:
- used daybreak to downgrade emuMMC to 12.0.0, version in settings is now 12.0.0|AMS M.19.3|E, with disable_ca_verification patch
  - connects successfully no error

**Comment by misson20000** [comment]
Thanks for the detailed troubleshooting! @HookedBehemoth, @thomasnet-mc, are either of you interested in porting the patch to 12.0.2 or should I do it? (although if you leave it to me it may take me a while...)

**Comment by InternalLoss** [comment]
This is interesting, since I had no issues on 12.0.2 with either browser or system SSL patches from the repository - 12.0.0 updated the browser and SSL module, 12.0.1/12.0.2 didn't.

**Comment by misson20000** [comment]
I've come up with some new verification tooling that shows the 12.0.2 ssl sysmodule patches are behaving exactly the same as on all other firmware versions. I suspect this may have been user error.
