### ISSUE TITLE
Disable CA Verification on 9.0.0 looks not working for me

### ISSUE THREAD

**Issue by RetroGamer74** [misson20000/exefs_patches#3]
**Which patch is broken?**
Disable CA verification for 9.0.0. Trying to use it in AMS 0.9.4. Expected behaviour not working.

**Describe the bug**
Using Charles Proxy, handshake is closed by NN without being able to send any request. Client SSL handshake failed: CA certificate could not be matched with a known, trusted CA (unknown_ca)

Same context but 8.1.0 is working ok.

**To Reproduce**
1. Copy exefs_patches in Atmosphere 0.9.4
2. Setup Charles Proxy using your own certificate
3. Wait for Switch to get Wifi Networks and send the requests
4. All handshakes are directly closed explaining CA Certificate could not be matched.

**Expected behavior**
Bypass CA verification and log in to NN using the certificate.

**Screenshots**

**Firmware version:**
9.0.0

**Additional context**
Nothing else.

Thank you very much.

**Comment by CosmoDX** [comment]
Me too but my firmware versión is 8.1.0.

**Comment by RetroGamer74** [comment]
It works ok. Sorry about this issue, but my SD Card was corrupted today, and I guess the folder was not being able to read it. Format it, and copy it again, everything works.

Thank you very much for your support.
