### ISSUE TITLE
Usage of this library

### ISSUE THREAD

**Issue by pccavar** [misson20000/exefs_patches#35]
Hello, I have a question regarding the usage of this library. Specifically, I would like to know how to disable SSL verification. Currently, when I place this file in the specified path on the SD card (sd:atmosphere/exefs_patches/*), it doesn't seem to work correctly. I am investigating whether I am doing something wrong. Do I need to make any additional configurations on the atmosphere side in order to use these patches?

If there is a website or any document resources available that provide descriptions or instructions related to this, I would greatly appreciate it if you could point me in the right direction.

That concludes my question. Any advice or information you can provide would be greatly appreciated. Thank you in advance.

**Comment by misson20000** [comment]
No additional configuration should be necessary. The patches may not have been updated for the system version you were on at the time. SSL verification should now be up to date for 16.0.3.
