### ISSUE TITLE
9.2.0

### ISSUE THREAD

**Issue by UnderRev0lved** [misson20000/exefs_patches#6]
**Which patch would you like ported?**
disable_ca_verification

**Which firmware versions would you like the patch ported to?**
9.2.0/9.1.0

**Comment by misson20000** [comment]
SSL sysmodule has actually not changed since 9.0.0. Can you check if the patch for 9.0.0 works on 9.2.0?

**Comment by UnderRev0lved** [comment]
From what I've seen on my test update to 9.1.0 broken the patch

**Comment by UnderRev0lved** [comment]
It work, sorry probaly had made a mistake in my setup.
